import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import React from "react";
import withRouter from "next/router";
export default function Home({ content }) {
  console.log(content);
  const ServeHeroBanner = () => {
    <p>Blah</p>;
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container">Biczka</div>
    </div>
  );
}

export async function getStaticProps() {
  const fetchit = await fetch("http://localhost:3000/api/front-page", {
    headers: {
      Authorization: `Bearer ${process.env.STRAPI_TOKEN}`,
    },
  });
  const content = await fetchit.json();
  return {
    props: {
      content,
    },
  };
}
